-- ============================================================
-- Migration: 001_initial_schema.sql
-- Project:   BPSC Engine — Examination Intelligence System
-- Purpose:   Create normalized tables to store AI-generated
--            topic ecosystems and their examination questions.
-- Run with:  psql -U postgres -d bpsc_db -f 001_initial_schema.sql
-- ============================================================

-- Enable pgcrypto so we can generate UUIDs server-side.
-- (uuid-ossp is the older alternative; pgcrypto ships with most installs.)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ──────────────────────────────────────────────────────────────
-- TABLE: question_ecosystems
-- Stores one row per AI-generated topic ecosystem.
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS question_ecosystems (
    -- Surrogate primary key — UUID v4 generated by the database.
    id                       UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The core BPSC/UPSC topic submitted by the user (e.g. "Indus Valley Civilisation").
    core_topic               TEXT        NOT NULL,

    -- Denormalised JSONB array of connected static concepts for fast reads.
    -- Example: ["Harappan Culture", "Urban Planning", "Trade Routes"]
    connected_static_concepts JSONB      NOT NULL DEFAULT '[]',

    -- When this ecosystem was persisted.
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Soft-delete / archiving support without losing data.
    is_archived              BOOLEAN     NOT NULL DEFAULT FALSE
);

-- Index for fast lookups by topic text (case-insensitive prefix search).
CREATE INDEX IF NOT EXISTS idx_ecosystems_core_topic
    ON question_ecosystems (lower(core_topic));

-- Index for chronological ordering on the list endpoint.
CREATE INDEX IF NOT EXISTS idx_ecosystems_created_at
    ON question_ecosystems (created_at DESC);


-- ──────────────────────────────────────────────────────────────
-- TABLE: generated_questions
-- Stores each individual examination question produced by the
-- AI for a given ecosystem.  Many questions → one ecosystem.
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS generated_questions (
    -- UUID primary key; the Go layer may supply one from the AI response
    -- or fall back to gen_random_uuid() if none was provided.
    id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key back to the parent ecosystem.
    ecosystem_id         UUID        NOT NULL
                             REFERENCES question_ecosystems (id)
                             ON DELETE CASCADE,   -- clean up questions when ecosystem is deleted

    -- The MCQ question stem.
    question_text        TEXT        NOT NULL,

    -- JSONB array of 4 answer strings preserves order without extra columns.
    -- Example: ["Option A", "Option B", "Option C", "Option D"]
    options              JSONB       NOT NULL DEFAULT '[]',

    -- 0-based index into the options array pointing to the correct answer.
    correct_option_index SMALLINT    NOT NULL CHECK (correct_option_index >= 0),

    -- AI-generated explanation / reasoning for the correct answer.
    explanation          TEXT        NOT NULL DEFAULT '',

    -- Enum-style column; enforced at application level (easy / medium / hard).
    difficulty           VARCHAR(10) NOT NULL DEFAULT 'medium'
                             CHECK (difficulty IN ('easy', 'medium', 'hard')),

    -- Subject area (e.g. "History", "Polity", "Economy").
    subject              TEXT        NOT NULL DEFAULT '',

    -- Ordering within the ecosystem (preserves AI-returned sequence).
    position             SMALLINT    NOT NULL DEFAULT 0,

    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Composite index: fetch all questions for an ecosystem, ordered by position.
CREATE INDEX IF NOT EXISTS idx_questions_ecosystem_position
    ON generated_questions (ecosystem_id, position);

-- Index to filter questions by difficulty across all ecosystems.
CREATE INDEX IF NOT EXISTS idx_questions_difficulty
    ON generated_questions (difficulty);

-- Index to filter by subject.
CREATE INDEX IF NOT EXISTS idx_questions_subject
    ON generated_questions (subject);


-- ──────────────────────────────────────────────────────────────
-- Rollback helper (comment out when running forward migration)
-- ──────────────────────────────────────────────────────────────
-- DROP TABLE IF EXISTS generated_questions;
-- DROP TABLE IF EXISTS question_ecosystems;
-- DROP EXTENSION IF EXISTS pgcrypto;
